global:
    dinkly_version: 1.22
admin:
    default_app: true
    app_name: Dinkly Admin
    app_description: Just a humble little PHP MVC Framework
    copyright: Dinkly
    base_href: /
    default_module: home 
api:
    app_name: Dinkly API
    base_href: /api
    default_module: api